version: '1.0.{build}'
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
after_build:
- dotnet pack -c Release
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master  
