version: '1.1.{build}'
before_build:
- cmd: dotnet restore
- dotnet version set --new-version {version}
build:
  publish_nuget: true
  verbosity: minimal
after_build:
- dotnet pack "Serilog.Sinks.Slack\project.json" -c Release
artifacts:
- path: Serilog.Sinks.Slack\bin\Release\*.nupkg
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master  
