version: '1.2.{build}'
before_build:
- cmd: dotnet restore
- cmd: cd Serilog.Sinks.Slack && dotnet version %APPVEYOR_BUILD_VERSION% && cd ..
build:
  publish_nuget: true
  verbosity: minimal
after_build:
- dotnet pack "Serilog.Sinks.Slack\project.json" -c Release
artifacts:
- path: Serilog.Sinks.Slack\bin\Release\*.nupkg
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master  
