name: Publish to nuget

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Serilog.Sinks.Slack/Serilog.Sinks.Slack.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}
